### ISSUE TITLE
Sync URL with enter and zoom for pagination

### ISSUE THREAD

**Issue by seanogdev** [instantsearch/instantsearch-googlemaps#12]
Is there a way to access the zoom and center values so I can keep it synced with pagination? Or am I being overly simplistic in thinking that that would possible?

**Comment by vvo** [comment]
Hi @miralize I am not sure to have enough context to be able to provide you an answer. Could you give me some more context on what you are trying to achieve on a UI point of view? Then we will see what's doable with this plugin

**Comment by seanogdev** [comment]
So I have a map that updates my list of the elements. Those elements are also paginated. But when I go to the next page, the map resets and so does the refined list of elements. 

Testable here https://lovindublin.com/restaurants

**Comment by vvo** [comment]
Thanks,
Can you give me a list of steps to do, and the expectations you have? That would help me a lot.

**Comment by seanogdev** [comment]
1. Zoom into a map that has only a few restaurants in them. 
2. Go to page 2 once its refined
3. See that a) the map resets and b) the entries reset.

**Comment by vvo** [comment]
Given the plugin feature set, this is currently expected.

Right now, both refinements (pagination) and moving the map will refine results and adapt the map to fit them. If you want more granular control, you will have to build it.

Sadly this plugin is not actively maintained for now. We do want to provide a very good map search plugin but it's tricky to implement so right now it's more of a BETA plugin. I will mention that the plugin is not maintained and we do not recommend it right now in the README and remove it from IS doc.

Then at some point we will build a good mapping plugin.

I would advise you to use the google map API yourself and plug into the instantsearch custom widget API (much like this widget is doing): https://community.algolia.com/instantsearch.js/documentation/#custom-widgets

I am sorry I cannot help you more on this, good luck.
