### ISSUE TITLE
instantsearch-googlemaps.js:169 Uncaught TypeError: t.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by lomholdt** [instantsearch/instantsearch-googlemaps#4]
I get this error when trying to run the script. Can't seem to make it work. Not sure if this is a general issue, or something is wrong on my end.

**Comment by lomholdt** [comment]
Realised I was using $('#map') instead of document.querySelector('#map')

**Comment by vvo** [comment]
Ah, great, where are you using this plugin?

Thanks!

**Comment by lomholdt** [comment]
I'm currently doing a new site for klinikker.dk. The current one is a prototype in wordpress. The new one is build with Django and we are using Algolia for search. We are doing a map of all the search results, and I found your plugin that seems to do exactly what I want. Will there be more development done on it? It could be awesome with more options for customising the map, and adding info windows and such.

And thanks for the plugin btw! :)

**Comment by vvo** [comment]
Yes we would like to add more features, we need clear definitions of what would be the needed features so please do open new issues with what you need or haave a look at the existing ones and comment on it, thanks!
