### ISSUE TITLE
Info windows on markers

### ISSUE THREAD

**Issue by lomholdt** [instantsearch/instantsearch-googlemaps#6]
As a developer I would like to be able to add a template for info windows for the markers on the map (https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple).

**Comment by vvo** [comment]
Hi Jonas, thanks for taking the time to give us feedback.

Would you like to contribute to this project? This is only wrapping https://github.com/tomchentw/react-google-maps

**Comment by vvo** [comment]
duplicate of #3
