### ISSUE TITLE
update cdn url

### ISSUE THREAD

**Issue by peteratbitscan** [instantsearch/instantsearch-googlemaps#7]
Your docs give the cdn url as;

//cdn.jsdelivr.net/instantsearch-googlemaps/0/instantsearch-googlemaps.min.js 

I think this needs to be updated to;

//cdn.jsdelivr.net/instantsearch-googlemaps/1/instantsearch-googlemaps.min.js

ta :)

**Comment by vvo** [comment]
Thanks a lot, now fixed
